### ISSUE TITLE
Make login form submit via enter

### ISSUE THREAD

**Issue by roosnic1** [wepublish/wepublish#110]
**Is your feature request related to a problem? Please describe.**
Pressing enter while the username or password field have the focus does not submit the login form.

**Describe the solution you'd like**
If either the username or password field have focus and the user presses enter the login form should be submitted.

**Comment by Itrulia** [comment]
Hey hey Nico! I just went through the "good first issue" issues and found this one. It seems like this is already the case now, can this be closed or is there still anything missing?
