### ISSUE TITLE
Update Node to latest LTS

### ISSUE THREAD

**Issue by michael-scheurer** [wepublish/wepublish#236]
**Describe the bug**
The current used node version is ^12.0.0. It should be updated to latest LTS version: https://nodejs.org/en/

**To Reproduce**
1. clone current repository
2. yarn install

**Expected behavior**
error wepublish@: The engine "node" is incompatible with this module. Expected version "^12.0.0".

**Desktop (please complete the following information):**
 - OS: ubuntu

**Comment by michael-scheurer** [comment]
Workaround: yarn install --ignore-engines

**Comment by roosnic1** [comment]
@tomaszdurka and @Itrulia do you already have a plan when you will upgrade to the next Node LTS?

Node v12 is already gone from the releases list of node https://nodejs.org/en/about/releases/

**Comment by Itrulia** [comment]
Afaik we want to get rid of @karma.run first. @elias-summermatter did some research IIRC

**Comment by Itrulia** [comment]
Should be done
