### ISSUE TITLE
publish command of oauth2

### ISSUE THREAD

**Issue by dev7ch** [wepublish/wepublish#24]
https://github.com/wepublish/wepublish/blob/61a168ca5ed6a601f0ff80a109716d1c0ea44ff9/package.json#L47

is this not supposed to be 
` "publish:oauth2": "yarn workspace @wepublish/oauth2 publish --access public --no-git-tag-version",` ?

**Comment by roosnic1** [comment]
It should. but oauth2 hasn't been published yet.
