### ISSUE TITLE
Wrong Subscription Start Date

### ISSUE THREAD

**Issue by michael-scheurer** [wepublish/wepublish#446]
**Describe the bug**
In the right hand user panel, the subscription "started" is wrong. See Screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/70939054/144881859-686dfe6e-3ad0-4ecd-b297-941773b5f93b.png)

**Additional context**
Version: 2.15.0-alpha.0

**Comment by roosnic1** [comment]
has been fixed and will be in the next release.
