### ISSUE TITLE
Missing re-try for a failed payment

### ISSUE THREAD

**Issue by michael-scheurer** [wepublish/wepublish#447]
**Is your feature request related to a problem? Please describe.**
It often happens, that a payment fails. For example due to a invalid entered credit card number. In this case, the end user should be able to re-try to pay.

**Comment by roosnic1** [comment]
@michael-scheurer i need a bit more information about this issue. What's the exact scenario for this?

**Comment by michael-scheurer** [comment]
Often, a user enters a wrong credit card number or uses an invalid one. In those cases the payment simply fails.
For now, the user has to restart the whole booking process again, because it's handled by creating these temp_ users.

But in my opinion the user should be able to just click a "re-try"-button which triggers a re-try-endpoint which restarts only the payment process and not the whole registration process.

Of course this solution requires to get rid of the temp_ user approach.

It would provide a lot of comfort to potential subscribers.

**Comment by roosnic1** [comment]
@michael-scheurer we'll solve the `temp_user` approach with the multiple subscriptions implementation. Once this is done you're able to call `registerMemberAndReceivePayment` as many times you want with the same email. From a we.publish point of view it's the responsibility of the front  end developers to implement something that allows the user to retry the registration.
