### ISSUE TITLE
Function: Disable/Enable peering

### ISSUE THREAD

**Issue by elias-summermatter** [wepublish/wepublish#471]
**Is your feature request related to a problem? Please describe.**
We should be able to disable a peering without deleting the peering. This is necessary in cases like Issue #470.  In case a peering is disabled all peered articles should temporary (until the peering is enabled again) be removed from any page. This allows to turn the peering off and o without getting a new id and the need of repeer all articles.

**Comment by roosnic1** [comment]
@elias-summermatter i agree. We opened an issue in our internal backlog for this. You'll be notified once the feature is implemented.

**Comment by Itrulia** [comment]
Was done as part of https://github.com/wepublish/wepublish/pull/598
