### ISSUE TITLE
Fetch multiple navigations

### ISSUE THREAD

**Issue by michael-scheurer** [wepublish/wepublish#499]
**Is your feature request related to a problem? Please describe.**
In case a frontend comes with multiple navigations, we should enhance the navigation endpoint to retrieve all navigations and adding the possibility to filter and or search. => Generalistic filter / sort possibility for endpoints should be achieved.

See for a good example: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#api-parameters

**Comment by roosnic1** [comment]
👍🏾 thanks. Added a story to our internal backlog. You'll be notified once the implementation is done.

**Comment by Itrulia** [comment]
Was done as part of https://github.com/wepublish/wepublish/pull/859 as needed for a demo
