### ISSUE TITLE
Users: Splitup Name to FirstName and LastName field

### ISSUE THREAD

**Issue by elias-summermatter** [wepublish/wepublish#501]
**Is your feature request related to a problem? Please describe.**
To have a clean member management system its essential that we got consistent data.

**Describe the solution you'd like**
Add a firstname field to the user.

**Comment by roosnic1** [comment]
I understand your point but i slightly disagree with it. I think the way it's currently implemented leads to more consistent data.

I took this [article](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) as inspiration for the `name` and `preferredName` fields on the user. 

This implementation allows for users to have their "legal" name in the system which covers use cases like:
- postal address
- invoices / receipts
and gives an optional field that can be used for a more informal communication.

At the moment i don't see the benefit of having the name separated in firstname and lastname. I'd like to know what benefits you see and what are the use cases that need the firstname separated from the lastname.

**Comment by elias-summermatter** [comment]
@roosnic1 its not my point its the point of Bajour. But yes i disagree with this article. ;-)  So how would you do a mail campaign that call the people by their first or last name? How do you ensure that people not just write their first/last name which by the way already happened. Wouldn't it be possible implement a new firstName field and if you don't want to use it for Tsüri.ch just leave it empty.

**Comment by michael-scheurer** [comment]
Furthermore it's not possible to sync with external apps such as Mailchimp and certainly dozens of other potential partners. You can always concatenate names together, but you cannot split them up.

**Comment by roosnic1** [comment]
Those are valid points. I'll discuss them internally with the team. But in any case this will not be a quick change because we use the concept of name and preferred name through out we.publish. Adding a first name field will most likely change that behavior. I'll get back to you next week.
