### ISSUE TITLE
Already registered user should be able to create a new subscription.

### ISSUE THREAD

**Issue by michael-scheurer** [wepublish/wepublish#532]
If a member lets his subscription expire or cancels it, but later wants to buy a new one, this is not possible with the existing endpoints so far.
This is a mandatory requirement from the point of view of the existing media. Because a new subscription cannot be purchased because the mail address is then already registered.
Moreover, it is a problem for existing editorial staff members who are registered as normal users.

**Comment by Itrulia** [comment]
Should be possible for a while now right?
