### ISSUE TITLE
Peered data should be cached

### ISSUE THREAD

**Issue by elias-summermatter** [wepublish/wepublish#534]
All external data from Peers should be stored and be delivered from a simple in memory cache (no fancy external cache required). The cache should be refresh in a definable time interval additionally it should be possible to invalidate cache by press of a button in the editor. This is very important to improve performance when we peer multiple articles with high latency peers or a peer is temporary unavailable. This should improve We.Publish's stability and performance by a lot. We could see a huge  performance improvement  for Bajour and Kultz when all peered articles have been removed from the front.

**Comment by LaurentAe** [comment]
https://wepublish.atlassian.net/browse/WPC-671
