### ISSUE TITLE
Author-List doesn't update upon removing an author

### ISSUE THREAD

**Issue by 0815pascal** [wepublish/wepublish#74]
**Expected behaviour:** Upon deleting an author, the author-list should automatically update whereby the recently deleted author shouldn't be displayed anymore. 

**Actual behaviour:** Upon deleting an author the recently deleted author is still being displayed in the list. It only disappears upon manually reloading the page. 

![8ab2935a-e824-4c0e-8db2-895829e3a556](https://user-images.githubusercontent.com/11842633/99073778-ce478000-25b6-11eb-9a38-50392c5959d2.gif)

**Comment by roosnic1** [comment]
Fixed
